### ISSUE TITLE
OpenSSL - Build .so files instead of .a

### ISSUE THREAD

**Issue by GensaGames** [VoiSmart/pjsip-android-builder#14]
Heya! 
Cool scripts for building OpenSSL, but there is some issue with build files. Can anyone help with parameters to build openssl .so files instead of .a. I know, that I can convert file .a to .so, but how safety is it? 
Cheers!

**Comment by GensaGames** [comment]
Note. That my colleague use another scritps - [OpenSSL-Scripts](https://github.com/xvtom/build-openssl-android), on mac, and got all files with .a and .so libraries in /usr/local/ssl/android-18/.  But i my case, with Ubuntu 14.04 they failed.

**Comment by Pauldic** [comment]
+1

**Comment by aenonGit** [comment]
not related to this repo. Closing
