### ISSUE TITLE
Upgrade for PJSIP 2.5

### ISSUE THREAD

**Issue by gotev** [VoiSmart/pjsip-android-builder#15]
PJSIP 2.5 has just been released: http://trac.pjsip.org/repos/milestone/release-2.5
Upgrade build scripts

**Comment by Pauldic** [comment]
+1

**Comment by gvlekke** [comment]
I made a pr for that #17 only thing is that the x86 can't build and isn't tested. At the moment I don't have the time to finish it. If you want you can finish it.
