### ISSUE TITLE
[Q] Faltal Exeption: UnsatisfiedLinkError: Native method not found: swig_module_init:()

### ISSUE THREAD

**Issue by cxrod** [VoiSmart/pjsip-android-builder#19]
Hello, 

I built successfully PJSIP thanks to you. Now I 'm testing with the sample application pjsua2 and I'm having this problem , you know what could be the solution?

> FATAL EXCEPTION: main
> java.lang.UnsatisfiedLinkError: Native method not found: io.cloudvoice.pjsiptest.pjsip.pjsua2.pjsua2JNI.swig_module_init:()V
>     at io.cloudvoice.pjsiptest.pjsip.pjsua2.pjsua2JNI.swig_module_init(Native Method)
>     at io.cloudvoice.pjsiptest.pjsip.pjsua2.pjsua2JNI.<clinit>(pjsua2JNI.java:2402)
>     at io.cloudvoice.pjsiptest.pjsip.pjsua2.Endpoint.<init>(Endpoint.java:68)
>     at io.cloudvoice.pjsiptest.pjsip.pjsua2.app.MyApp.<clinit>(MyApp.java:293)
>     at io.cloudvoice.pjsiptest.pjsip.pjsua2.app.MainActivity.onCreate(MainActivity.java:93)
>     at android.app.Activity.performCreate(Activity.java:5133)
>     at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1087)
>     at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2175)
>     at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2261)
>     at android.app.ActivityThread.access$600(ActivityThread.java:141)
>     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1256)
>     at android.os.Handler.dispatchMessage(Handler.java:99)
>     at android.os.Looper.loop(Looper.java:137)
>     at android.app.ActivityThread.main(ActivityThread.java:5103)
>     at java.lang.reflect.Method.invokeNative(Native Method)
>     at java.lang.reflect.Method.invoke(Method.java:525)
>     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:737)
>     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:553)
>     at dalvik.system.NativeStart.main(Native Method)

**Comment by aenonGit** [comment]
might be you have compiled for the wrong architecture?

**Comment by datso** [comment]
It is also possible that you didn't copy a new version of java sources, e.g. pjsip-apps/src/swig/java/android/app/src/main/java/org/pjsip/pjsua2/app

**Comment by eduardobonfa** [comment]
I got the new version of codes, but i'm trying to implement an application for linux, but i thought it would be the same problem. Do you have any tutorial or example of using pjsua in netbeans?

**Comment by arekz-mj** [comment]
Did you find solution for your problem?

**Comment by salSB** [comment]
ssss
