### ISSUE TITLE
video not working in pjsip 2.6 in android

### ISSUE THREAD

**Issue by yuvaraj119** [VoiSmart/pjsip-android-builder#21]
I used pjsip 2.6,openh264 latest version and openssl-h it got build and gave me all the .so files for armeabi,v7a,64-v8a and intel x86,64. But when i make a call it takes a lot of time for call to get initialize. Voice call is working good but the video is not working.

Before this i tried with older version pjsip 2.4.5,openh264 1.0.0 and openssl-h in this video and voice call is working good but with one way calling issue. In this openh264 1.0.0 give .so files for 32 bit only no support for 64 bit.

Has any one who has faced this issue with latest build of pjsip 2.6,openh264 latest version and openssl-h. 
there are no error log while building the .so files and in android project also there is no crash while calling only video is not getting initialize. 
Thank You.

**Comment by Shruti7032** [comment]
HI Yuvraj
I am facing the similar issue as you have mentioned above. Please let me know if you found the solution for it.

**Comment by datso** [comment]
@yuvaraj119 @Shruti7032 I think that this is a configuration issue, and it could be solved it by setting following configuration:

cfg.getVideoConfig().setAutoShowIncoming(true);
cfg.getVideoConfig().setAutoTransmitOutgoing(true);

**Comment by aenonGit** [comment]
Also note that openh264 1.6.0 should be good, while the v1.7.0 has some issues
