### ISSUE TITLE
build error openssl-1.1.0e

### ISSUE THREAD

**Issue by boostiewj** [VoiSmart/pjsip-android-builder#22]
build  openssl-1.0.2k success,but build openssl-1.1.0e  error

./openssl-build /home/user/android-ndk-r12b /home/user/and_libs/openssl-1.1.1.0e 14 armeabi-v7a 4.9 /home/user/and_libs/armeabi-v7a

Configuring for android-armv7
Warning! target android-armv7 doesn't exist!
Usage: Configure [no-<cipher> ...] [enable-<cipher> ...] [-Dxxx] [-lxxx] [-Lxxx] [-fxxx] [-Kxxx] [no-hw-xxx|no-hw] [[no-]threads] [[no-]shared] [[no-]zlib|zlib-dynamic] [no-asm] [no-dso] [no-egd] [sctp] [386] [--prefix=DIR] [--openssldir=OPENSSLDIR] [--with-xxx[=vvv]] [--config=FILE] os/compiler[:flags]

NOTE: If in doubt, on Unix-ish systems use './config'.

**Comment by GnudMasterIT** [comment]
i build openssl-1.0.2l success, i have libcrypto.a and libssl.a, then what can I do with two this file ?

**Comment by boostiewj** [comment]
I aslo build openssl-1.0.2l success,But 1.1.0e error!

**Comment by RaduPaun** [comment]
I've also build openssl-1.0.2 with success with android ndk r12b.
But I can't build openssl-1.1.0f. I've tried with ndk-r12b and ndk-r15b and in both cases I received the same warning: 
Warning! target android-armv7 doesn't exist!
..
Usage: Configure [no-<cipher> ...] [enable-<cipher> ...] [-Dxxx] [-lxxx] [-Lxxx] [-fxxx] [-Kxxx] [no-hw-xxx|no-hw] [[no-]threads] [[no-]shared] [[no-]zlib|zlib-dynamic] [no-asm] [no-dso] [no-egd] [sctp] [386] [--prefix=DIR] [--openssldir=OPENSSLDIR] [--with-xxx[=vvv]] [--config=FILE] os/compiler[:flags]

**Comment by aenonGit** [comment]
You should try with pjsip 2.7
https://trac.pjsip.org/repos/milestone/release-2.7
