### ISSUE TITLE
Can't Compile for "mips" "arm64-v8a" "x86_64" "mips64" archs.

### ISSUE THREAD

**Issue by dalwadi2** [VoiSmart/pjsip-android-builder#24]
I've followed below instructions but can't get these 4 arch files.
```
TARGET_ARCHS=("armeabi" "armeabi-v7a" "x86" "mips")
TARGET_ANDROID_API=21
SETUP_PACKAGES=0
DOWNLOAD_NDK=0
DOWNLOAD_SDK=0
DOWNLOAD_ANDROID_APIS=0
DOWNLOAD_PJSIP=1
DOWNLOAD_SWIG=0
```
after executing `./build` , I get this error message _cp: cannot stat '/home/android/../../../pjsip-android-builder-master/libyuv-android/libs/mips/libyuv.so': No such file or directory_
Even when i executed `./prepare-build-system; ` command I saw in terminal that only 3 arch files only compiled in **libyuv-android** Directory.
can you please help me to generate all arch compiled files ASAP.
thanks

**Comment by spali90** [comment]
did you find a solution ? I am experiencing same issue.

**Comment by aenonGit** [comment]
have you downloaded the LIBYUV library? If so, try disabling video support in the configuration and delete libyuv and openh264 from the build scripts

**Comment by dalwadi2** [comment]
@aenonGit yes, I've done that one.
can you send me the .so files for those Architectures?

**Comment by aenonGit** [comment]
From pjsip 2.6 on, libyuv is included, there is no need to build it from scratch anymore. Use the 2.6+ version of pjsip
