### ISSUE TITLE
 G729 codec is disabled...yes

### ISSUE THREAD

**Issue by shehrazjazib** [VoiSmart/pjsip-android-builder#26]
I followed the instruction and add patch with pjsip project. When i execute the build command i get this message : **Checking if g729 codec is disabled...yes**. 

Please guide me  what should i do to integrate G729 codec with my pjsip project. 

Thanks in advance

**Comment by aenonGit** [comment]
Have you executed the build-with-g729 script?

**Comment by aenonGit** [comment]
besides have you correctly applied the g729 patch? When you execute the `build-with-g729` script if you read the log does it says `aconfigure unrecognized options: --enable-g729-codec`. If so the patch has not been properly applied.

**Comment by aenonGit** [comment]
check next release
