### ISSUE TITLE
How to copy files from vagrant VM to my host machine

### ISSUE THREAD

**Issue by shehrazjazib** [VoiSmart/pjsip-android-builder#27]
I build the libraries successfully, but don't know how to copy these libraries from VM to my host machine. 
Kindly guide me .
Thanks in advance

**Comment by ivanovsuper** [comment]
`scp -r -P 2200 vagrant@127.0.0.1:/home/vagrant/pjsip-build/ .`
default password is `vagrant`

**Comment by aenonGit** [comment]
Don't use vagrant. Use a docker container (ubuntu) and mount the repo as an external volume from your host machine
