### ISSUE TITLE
G.729 patch not working with PJSIP v2.9

### ISSUE THREAD

**Issue by ShlomieRottenberg** [VoiSmart/pjsip-android-builder#35]
When I try to use the G.729 patch with PJSIP v2.9 the build doesn't work. After looking through the code, I think the issue is that in install.sh (in the G.729 patch folder) has this code 
`if [ "$PJSIP_VERSION" == "2.8" ]
then
    cp g729.patch $PJPROJECT_BASE_FOLDER
else
    cp g729_old.patch $PJPROJECT_BASE_FOLDER/g729.patch
fi`

when it should be 
`
 [ "$PJSIP_VERSION" >= "2.8" ]
`

The code i wrote is psuedocode as I am not sure the exact syntax required to make this change

**Comment by aenonGit** [comment]
you might be right. I'll take a look

**Comment by aenonGit** [comment]
try latest develop even if it's not released yet but feel free to reopen. Closing for now

**Comment by lahirutm** [comment]
this builds are not working with latest Android 10 version. Do you have fix for that ?

**Comment by aenonGit** [comment]
expand your build environment
