### ISSUE TITLE
openssl library not found

### ISSUE THREAD

**Issue by NameSpace5** [VoiSmart/pjsip-android-builder#37]
Hello, I build it as your env, and it goes well if target api is 25,but it doesn't work if I change it to 19, the error is 'openssl library not found',can you tell me what to do if I want build with 19?

**Comment by aenonGit** [comment]
try tdowngrading the openssl version and removing the 64bit archs

**Comment by NameSpace5** [comment]
thx, I checkout branch of tag 2.0，and set ssl ndk to r10e，it worked for 19.

**Comment by NameSpace5** [comment]
hello, I rebuild it by the latest branch with target api 23, i try to build arm64 but failed. we chat among two phone, but it keep mute after linked.  can you help me more?

09-19 22:32:31.568 382-1104/? E/dirac.effect_dirac: first processing
09-19 22:32:31.592 18372-18372/com.view.asim.enterprise E/MediaPlayer: Should have subtitle controller already set
09-19 22:32:31.609 382-1104/? E/AudioALSAPlaybackHandlerBase: openPcmDriver(), pcm_start(0xeaa8db00) fail due to cannot start channel: Broken pipe
09-19 22:32:31.642 382-1104/? E/AudioALSAPlaybackHandlerBase: -getHardwareBufferInfo pcm_get_htimestamp fail, ret = -1, pcm_get_error = cannot start channel: Broken pipe
09-19 22:32:31.643 382-1104/? E/AudioALSAPlaybackHandlerBase: -getHardwareBufferInfo pcm_get_htimestamp fail, ret = -1, pcm_get_error = cannot start channel: Broken pipe
09-19 22:32:31.758 382-1104/? E/AudioALSAStreamOut: -getPresentationPosition(), no playback handler, *frames = 43867136, return
09-19 22:32:31.761 18372-18372/com.view.asim.enterprise E/SensorManager: unRegisterListener by ak.im.ui.activity.ChatActivity
09-19 22:32:31.762 994-2733/? E/Sensors: handleToDriver handle(7)
09-19 22:32:31.799 382-1104/? E/AudioALSAPlaybackHandlerBase: openPcmDriver(), pcm_start(0xeaa8cec0) fail due to cannot start channel: Broken pipe
09-19 22:32:31.831 382-1104/? E/AudioALSAPlaybackHandlerBase: -getHardwareBufferInfo pcm_get_htimestamp fail, ret = -1, pcm_get_error = cannot start channel: Broken pipe
09-19 22:32:31.832 382-1104/? E/AudioALSAPlaybackHandlerBase: -getHardwareBufferInfo pcm_get_htimestamp fail, ret = -1, pcm_get_error = cannot start channel: Broken pipe
09-19 22:32:31.924 18372-18372/com.view.asim.enterprise E/SensorManager: RegisterListener PROXIMITY type:8 delay:200000us by org.pjsip.pjsua2.app.CallSensorManager
09-19 22:32:31.925 994-2293/? E/Sensors: handleToDriver handle(7)
09-19 22:32:31.925 994-2293/? E/Sensors: handleToDriver handle(7)
09-19 22:32:31.925 994-2293/? E/Sensors: new setDelay handle(7),ns(200000000)m, error(0), index(6)
09-19 22:32:31.925 994-2293/? E/PROXIMITY: PS batch: handle:7, en:0,samplingPeriodNs:200000000, maxBatchReportLatencyNs:0 
09-19 22:32:31.925 994-2293/? E/Sensors: sensor 7 go to common batch
09-19 22:32:31.925 994-2293/? E/Sensors: handleToDriver handle(7)
09-19 22:32:31.955 994-1014/? E/LIGHT: AmbiLightSensor: unknown event (type=2, code=2)
09-19 22:32:31.955 994-1014/? E/LIGHT: AmbiLightSensor: unknown event (type=2, code=1)
09-19 22:32:31.955 994-1014/? E/LIGHT: AmbiLightSensor: invalid EV_SYN
09-19 22:32:31.955 994-1014/? E/PROXIMITY: ProximitySensor: report prox event
09-19 22:32:31.956 18372-18372/com.view.asim.enterprise E/SensorManager: RegisterListener ACCELEROMETER type:1 delay:200000us by org.pjsip.pjsua2.app.AccelerometerListener$1
09-19 22:32:31.957 994-2800/? E/Sensors: handleToDriver handle(0)
09-19 22:32:31.957 994-2800/? E/Sensors: handleToDriver handle(0)
09-19 22:32:31.959 994-2800/? E/Sensors: new setDelay handle(0),ns(200000000)m, error(0), index(2)
09-19 22:32:31.959 994-2800/? E/Accel: ACC batch: handle:0, en:0,samplingPeriodNs:200000000 maxBatchReportLatencyNs:0 
09-19 22:32:31.959 994-2800/? E/Sensors: sensor 0 go to common batch
09-19 22:32:31.959 994-2800/? E/Sensors: handleToDriver handle(0)
09-19 22:32:31.988 18372-18372/com.view.asim.enterprise E/RecyclerView: No adapter attached; skipping layout
09-19 22:32:32.027 18372-18372/com.view.asim.enterprise E/RecyclerView: No adapter attached; skipping layout
09-19 22:32:32.037 382-16256/? E/AudioALSAStreamIn: checkOpenStreamChannels(), wrong channels 0x10, use 0xc instead.
09-19 22:32:32.037 382-16256/? E/AudioALSAStreamManager: -openInputStream(), set fail, return NULL
09-19 22:32:34.090 382-18828/? E/MP3Extractor: Read mp3 frame may timeout , time consumed = 1053
09-19 22:32:34.848 382-1104/? E/AudioALSAStreamOut: -getPresentationPosition(), no playback handler, *frames = 44003328, return
09-19 22:32:34.990 382-1104/? E/AudioALSAStreamOut: -getPresentationPosition(), no playback handler, *frames = 44004352, return
09-19 22:32:35.080 382-1104/? E/AudioALSAPlaybackHandlerBase: openPcmDriver(), pcm_start(0xeaa8d080) fail due to cannot start channel: Broken pipe
09-19 22:32:35.125 382-1104/? E/AudioALSAPlaybackHandlerBase: -getHardwareBufferInfo pcm_get_htimestamp fail, ret = -1, pcm_get_error = cannot start channel: Broken pipe
09-19 22:32:35.127 382-1104/? E/AudioALSAPlaybackHandlerBase: -getHardwareBufferInfo pcm_get_htimestamp fail, ret = -1, pcm_get_error = cannot start channel: Broken pipe
09-19 22:32:35.159 382-1104/? E/AudioFlinger: getNextBuffer, get null buffer
09-19 22:32:35.249 382-1104/? E/dirac.effect_dirac: first processing
09-19 22:32:35.287 382-1104/? E/AudioALSAPlaybackHandlerBase: openPcmDriver(), pcm_start(0xeaa8d080) fail due to cannot start channel: Broken pipe
09-19 22:32:35.289 382-1104/? E/AudioALSAPlaybackHandlerBase: -getHardwareBufferInfo pcm_get_htimestamp fail, ret = -1, pcm_get_error = cannot start channel: Broken pipe
09-19 22:32:35.291 382-1104/? E/AudioALSAPlaybackHandlerBase: -getHardwareBufferInfo pcm_get_htimestamp fail, ret = -1, pcm_get_error = cannot start channel: Broken pipe
09-19 22:32:38.937 18372-18372/com.view.asim.enterprise E/SensorManager: RegisterListener PROXIMITY type:8 delay:200000us by ak.im.ui.activity.ChatActivity
09-19 22:32:38.938 994-1973/? E/Sensors: handleToDriver handle(7)
09-19 22:32:38.938 994-1973/? E/Sensors: go to batchsensor
09-19 22:32:39.213 18372-18372/com.view.asim.enterprise E/SensorManager: unRegisterListener by org.pjsip.pjsua2.app.CallSensorManager
09-19 22:32:39.213 994-1045/? E/Sensors: handleToDriver handle(7)
09-19 22:32:39.213 994-1045/? E/Sensors: handleToDriver handle(7)
09-19 22:32:39.213 994-1045/? E/Sensors: new setDelay handle(7),ns(200000000)m, error(0), index(6)
09-19 22:32:39.213 994-1045/? E/PROXIMITY: PS batch: handle:7, en:0,samplingPeriodNs:200000000, maxBatchReportLatencyNs:0 
09-19 22:32:39.213 994-1045/? E/Sensors: sensor 7 go to common batch
09-19 22:32:39.214 18372-18372/com.view.asim.enterprise E/SensorManager: unRegisterListener by org.pjsip.pjsua2.app.AccelerometerListener$1
09-19 22:32:39.214 994-1973/? E/Sensors: handleToDriver handle(0)

**Comment by NameSpace5** [comment]
filter error as follow 

09-19 22:36:38.519 382-1104/? E/AudioALSAStreamOut: -getPresentationPosition(), no playback handler, *frames = 44546048, return
09-19 22:36:38.660 382-1104/? E/AudioALSAStreamOut: -getPresentationPosition(), no playback handler, *frames = 44547072, return
09-19 22:36:38.707 382-1104/? E/AudioALSAPlaybackHandlerBase: openPcmDriver(), pcm_start(0xeaa8dcc0) fail due to cannot start channel: Broken pipe
09-19 22:36:38.756 382-1104/? E/AudioALSAPlaybackHandlerBase: -getHardwareBufferInfo pcm_get_htimestamp fail, ret = -1, pcm_get_error = cannot start channel: Broken pipe
09-19 22:36:38.758 382-1104/? E/AudioALSAPlaybackHandlerBase: -getHardwareBufferInfo pcm_get_htimestamp fail, ret = -1, pcm_get_error = cannot start channel: Broken pipe
09-19 22:36:38.807 382-1104/? E/AudioFlinger: getNextBuffer, get null buffer
09-19 22:36:38.919 382-1104/? E/dirac.effect_dirac: first processing
09-19 22:36:38.958 382-1104/? E/AudioALSAPlaybackHandlerBase: openPcmDriver(), pcm_start(0xeaa8dcc0) fail due to cannot start channel: Broken pipe
09-19 22:36:38.960 382-1104/? E/AudioALSAPlaybackHandlerBase: -getHardwareBufferInfo pcm_get_htimestamp fail, ret = -1, pcm_get_error = cannot start channel: Broken pipe
09-19 22:36:38.962 382-1104/? E/AudioALSAPlaybackHandlerBase: -getHardwareBufferInfo pcm_get_htimestamp fail, ret = -1, pcm_get_error = cannot start channel: Broken pipe
09-19 22:36:39.596 382-1104/? E/dirac.effect_dirac: first processing
09-19 22:36:39.634 382-1104/? E/AudioALSAPlaybackHandlerBase: openPcmDriver(), pcm_start(0xeaa8dcc0) fail due to cannot start channel: Broken pipe
09-19 22:36:39.674 382-1104/? E/AudioALSAPlaybackHandlerBase: -getHardwareBufferInfo pcm_get_htimestamp fail, ret = -1, pcm_get_error = cannot start channel: Broken pipe
09-19 22:36:39.676 382-1104/? E/AudioALSAPlaybackHandlerBase: -getHardwareBufferInfo pcm_get_htimestamp fail, ret = -1, pcm_get_error = cannot start channel: Broken pipe
09-19 22:36:43.366 18372-18372/com.view.asim.enterprise E/SensorManager: RegisterListener PROXIMITY type:8 delay:200000us by ak.im.ui.activity.ChatActivity
09-19 22:36:43.369 994-1048/? E/Sensors: handleToDriver handle(7)
09-19 22:36:43.370 994-1048/? E/Sensors: go to batchsensor
09-19 22:36:43.685 18372-18372/com.view.asim.enterprise E/SensorManager: unRegisterListener by org.pjsip.pjsua2.app.CallSensorManager
09-19 22:36:43.685 994-2259/? E/Sensors: handleToDriver handle(7)
09-19 22:36:43.685 994-2259/? E/Sensors: handleToDriver handle(7)
09-19 22:36:43.685 994-2259/? E/Sensors: new setDelay handle(7),ns(200000000)m, error(0), index(6)
09-19 22:36:43.685 994-2259/? E/PROXIMITY: PS batch: handle:7, en:0,samplingPeriodNs:200000000, maxBatchReportLatencyNs:0 
09-19 22:36:43.685 994-2259/? E/Sensors: sensor 7 go to common batch
09-19 22:36:43.686 18372-18372/com.view.asim.enterprise E/SensorManager: unRegisterListener by org.pjsip.pjsua2.app.AccelerometerListener$1
09-19 22:36:43.687 994-1011/? E/Sensors: handleToDriver handle(0)

**Comment by NameSpace5** [comment]
it seems that openssl didn't work?

**Comment by NameSpace5** [comment]
Got it, keep the same version while build openH264 and openssl.
