### ISSUE TITLE
Package 'oracle-java8-installer' has no installation candidate

### ISSUE THREAD

**Issue by taime** [VoiSmart/pjsip-android-builder#38]
Ubuntu 18.

Got error: 
Package 'oracle-java8-installer' has no installation candidate

(The problem with `apt-get install oracle-java8-installer`)

May be should use this:
can be installed with: `sudo apt install default-jre` OR `sudo apt install openjdk-11-jre-headless` OR `sudo apt install openjdk-8-jre-headless`

Here is stackoverflow answer: 
https://askubuntu.com/questions/790671/oracle-java8-installer-no-installation-candidate

For ubuntu 16, 14 and etc...
````
sudo add-apt-repository ppa:webupd8team/java
sudo apt-get update
sudo apt-get install oracle-java8-installer
````

For Debian

````
su -
echo "deb http://ppa.launchpad.net/webupd8team/java/ubuntu xenial main" | tee /etc/apt/sources.list.d/webupd8team-java.list
echo "deb-src http://ppa.launchpad.net/webupd8team/java/ubuntu xenial main" | tee -a /etc/apt/sources.list.d/webupd8team-java.list
apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys EEA14886
apt-get update
apt-get install oracle-java8-installer
exit
````

**Comment by MikePryadko** [comment]
Why Oracle? Is it possible to use OpenJDK? If not - why??

**Comment by aenonGit** [comment]
you can try it and let us know

**Comment by gapkalov** [comment]
> you can try it and let us know

Your script is completely broken:
Got error:
Package 'oracle-java8-installer' has no installation candidate

 please fix it.

**Comment by aenonGit** [comment]
check release `2.2.0` and commit d61cc7e2
