### ISSUE TITLE
Execute ./prepare-build-system error

### ISSUE THREAD

**Issue by cs1086** [VoiSmart/pjsip-android-builder#47]
Reading package lists... Done
E: Failed to fetch http://ports.ubuntu.com/ubuntu-ports/dists/jammy/multiverse/binary-i386/Packages  404  Not Found [IP: 185.125.190.39 80]
E: Failed to fetch http://ports.ubuntu.com/ubuntu-ports/dists/jammy-updates/multiverse/binary-i386/Packages  404  Not Found [IP: 185.125.190.39 80]
E: Failed to fetch http://ports.ubuntu.com/ubuntu-ports/dists/jammy-backports/universe/binary-i386/Packages  404  Not Found [IP: 185.125.190.39 80]
E: Failed to fetch http://ports.ubuntu.com/ubuntu-ports/dists/jammy-security/multiverse/binary-i386/Packages  404  Not Found [IP: 185.125.190.39 80]
E: Some index files failed to download. They have been ignored, or old ones used instead.

**Comment by aenonGit** [comment]
haven't tried yet on latest ubuntu. Could you try on a lower version of the OS?

**Comment by palla89** [comment]
We have encountered the same problem trying the build on an M1 MacBook.
To solve this issue you have to pull the amd64 ubuntu image instead of the arm64, running:
```
docker pull --platform linux/amd64 ubuntu:latest
docker run -it --name pjsip-builder -v .....
```
and then the ```./prepare-build-system``` command will work fine (but slowly)

**Comment by aenonGit** [comment]
for docker slowness it is a known issue on macOS, it can be fixed (?) by changing the `Choose file sharing implementation for your containers` to `VirtioFS`
